# Generated by Django 5.2.4 on 2025-08-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
